### ISSUE TITLE
TK 010 - CRITERIOS DE ACEPTACION

### ISSUE THREAD

**Issue by GERGUSCANO** [ISPC-TSDW/Libroteka.app#10]
Realizar los criterios de aceptacion

**Comment by rominasolhaag** [comment]
Los criterios de aceptacion los realizo Vale, pero los revise y deje sugerencias al privado porque no puedo acceder a mi correo para dejarselas en el documento.

**Comment by rominasolhaag** [comment]
https://docs.google.com/spreadsheets/d/1Ek99tYoibZMLKyZhNBWD7Nqc_ZLrAqDHJKAJ3VcsMk0/edit?gid=0#gid=0

Comentarios sobre los criterios de aceptacion y los pase a imperativo para que queden todos en el mismo tiempo y sea mas facil leer, si les parece procedan, aclaro que solo modifique lo hecho, muy buen trabajo Vale. 
a medida que vayamos teniendo mas definiciones agregamos mas escenarios :) @valetommasini  @GERGUSCANO :
**#US01** 
Dejaria el criterio de aceptacion 
Nro | Criterio de aceptación (Título) | Contexto | Evento | Resultado / Comportamiento esperado|
-- | -- | -- | -- | --
1 | registro exitoso | Dado que el usuario quiere registrarse como cliente | cuando coloca los datos correctamente | entonces el registro es exitoso.
3 | registro con errores |  Dado que el usuario quiere registrarse como cliente | cuando ingresa los datos de manera incorrecta | entonces el sistema muestra al usuario mensaje informando que datos debe corregir.

**#US02**

Nro | Criterio de aceptación (Título) | Contexto | Evento | Resultado / Comportamiento esperado|
-- | -- | -- | -- | --
1 | log in exitoso | Dado que un usuario registrado quiere iniciar sesion | cuando ingresa los datos correctamente | entonces inicia sesion de manera exitosa y  el sistema redirige al home de la app.
2 | log in con errores | dado que un usuario registrado quiere iniciar sesion | cuando ingresa datos erroneos | entonces el sistema muestra un mensaje de error indicando que las credenciales son incorrectas.
3 | seguridad y proteccion | dado que soy un usuario que se quiere registrar | intento acceder a una página o recurso protegido sin iniciar sesión | debería redirigirme automáticamente a la pantalla de inicio de sesión.


**Al 3 lo interpreto como lo voy a detallar abajo**
Nro | Criterio de aceptación (Título) | Contexto | Evento | Resultado / Comportamiento esperado|
-- | -- | -- | -- | --
3 | seguridad y proteccion | Dado que usuario no registrado quiere iniciar sesion | cuando ingresa sus credenciales | entonces el sistema deberia mostrar un mensaje indicando que no esta registrado.


**ahora lo lei de nuevo y creo que lo entendi, pero igual deje el escenario anterior:**

Nro | Criterio de aceptación (Título) | Contexto | Evento | Resultado / Comportamiento esperado|
-- | -- | -- | -- | --
3 | seguridad y proteccion | dado a un usuario sin autenticarse | cuando intenta acceder a una página o recurso protegido | entonces el sistema redirige automáticamente a la pantalla de inicio de sesión.


**En el caso de la  #US03* dejaria el primer ejemplo y los ultimos dos*
Criterios de aceptación
--
Nro | Criterio de aceptación (Título) | Contexto | Evento | Resultado / Comportamiento esperado|
-- | -- | -- | -- | --
1 | Búsqueda por título | Dado que ingresa en el buscador el titulo del libro  | cuando el titulo del libro se encuentra | Entonces el sistema muestra una lista de libros que coinciden con el título ingresado, ordenados alfabaticamente.||
2 | Busqueda por autor | Dado que ingresa en el buscador el autor de un libro | cuando el titulo del libro se encuentra  | Entonces el sistema muestra una lista de libros que coinciden con el autor ingresado, ordenados alfabeticamente.||
3 | Busqueda por genero | Dado que ingresa en el buscador un genero de libro| cuando el titulo del libro se encuentra | Entonces el sistema muestra una lista de libros que coinciden con el genero literario ingresado.||
4| Busqueda no encontrada | Dado que ingresa en el buscador un dato inexistente | cuando no encuentra el dato | Entonces el sistema muestra un mensaje de "No se encontraron resultados"
5| busqueda insensible o flexible | Dado que se ingresa el nombre del libro sin respetar mayúsculas o sin respetar el nombre exacto del libro | Cuando el sistema reconoce las palabras o el nombre del libro | Entonces el buscador muestra una lista de libros que coincidan con la palabra ingresada.


**#US04**
Nro | Criterio de aceptación (Título) | Contexto | Evento | Resultado / Comportamiento esperado|
-- | -- | -- | -- | --
1 | Filtrar por calificación | Dado que la aplicación ofrece un rango de calificaciones o un mínimo de calificaciones para elegir | Cuando se elige el rango deseado de calificaciones | Entonces se muestran libros con calificaciones en el rango o por encima de la calificación mínima seleccionada. |
2 | Filtrar por precio | Dado que la aplicación ofrece un rango de precios o un mínimo de precio para elegir | Cuando se elige el rango de precios que interesa o el mínimo de precio que se está dispuesto a pagar | Entonces el sistema muestra una lista de libros que coinciden con el rango de precios seleccionado.|
3 | Filtrar por popularidad | Dado que la aplicación ofrece la opción de ordenar por popularidad en vez de alfabéticamente | Cuando se elige el filtro por popularidad | Entonces el sistema muestra una lista de libros ordenada por popularidad y no alfabéticamente
