### ISSUE TITLE
#US10 - HOME

### ISSUE THREAD

**Issue by valetommasini** [ISPC-TSDW/Libroteka.app#20]
**Como** usuario de la aplicación "Libroteka", **quiero** buscar un libro específico utilizando criterios como género, autor o título, **para** encontrar rápidamente el libro que estoy buscando.

**-En el Caso** que el usuario quiera visualizar los libros de la plataforma **cuando** haga click en el botón home del menú bottom **a continuación**, encontrará un pantalla con los libros disponibles en forma de carrusel.
-**En el Caso** que el usuario quiera buscar por categorías **cuando** haga click en los botones del carrusel en el margen superior  **a continuación**, se filtraran los libros del género que haya seleccionado.

**Comment by GERGUSCANO** [comment]
**Como** usuario de la aplicación "Libroteka", **quiero** una pantalla de home intuitiva que me muestre un carrusel con los libros destacados, iconos de acceso rápido a ofertas, cupones de descuentos, mas vendidos y ver más , **para** encontrar rápidamente lo que estoy buscando.

- El usuario debe poder acceder a una pantalla de home intuitiva de rápido acceso a las diferentes funcionalidades de la aplicación 

- El usuario debe poder visualizar diferentes iconos por los que pueda ingresar a las diferentes ofertas, destacados, más vendidos entre otros.
