### ISSUE TITLE
#US10 - TK01 - Añadir libros a favoritos

### ISSUE THREAD

**Issue by gsgesto** [ISPC-TSDW/Libroteka.app#56]
Como usuario registrado, quiero añadir y quitar libros de mi estante de favoritos.

**Comment by gsgesto** [comment]
https://github.com/ISPC-TSDW/Libroteka.app/pull/95

**Comment by gsgesto** [comment]
https://github.com/ISPC-TSDW/Libroteka.app/pull/97

**Comment by rominasolhaag** [comment]
#20
