### ISSUE TITLE
TK 008 - REGISTRO DE LAS HISTORIAS DE USUARIO

### ISSUE THREAD

**Issue by GERGUSCANO** [ISPC-TSDW/Libroteka.app#8]
Registrar en el formulario IEEE830, las historias de usuario, product backlog

**Comment by JuanPSuarez** [comment]
https://docs.google.com/document/d/1lHNEy0loyoqiZgPb7UqBYLvoccdrFa9LuBH5xz8ADTo/edit#heading=h.bl7rsxnm3bgp
